### ISSUE TITLE
[Feature Request] Ability to log out of Booksonic Air website

### ISSUE THREAD

**Issue by raviwarrier** [popeen/Booksonic-Air#41]
I was unable to find a way to log out of booksonic air. If there's a way, perhaps, please let me know. If there isn't, then please have a logout button.

Thanks.

**Comment by gandalf15** [comment]
Quick solution. In your browser type in the URL "/logout" after the port number. So, it will be `yourIP:4040/logout` assuming your port is the default 4040. I was looking for the log out button too.

**Comment by raviwarrier** [comment]
Thanks Gandalf! I had to clear my cache and cookies to do it yesterday. :)

**Comment by popeen** [comment]
Added in 0456d7e81fa4ad8f097c110822c23200426da8af
