### ISSUE TITLE
CSS not working on Safari (macOS 12)

### ISSUE THREAD

**Issue by fisherwei** [popeen/Booksonic-Air#53]
## Problem description

css is not working on safari browser.

### Steps to reproduce

Open, and login.

## System information

 * **Airsonic version**: 2112.1.0 – December 12, 2021, based on Airsonic 8b28366
 * **Operating system**: macOS 12.0.1
 * **Java version**: Apache Tomcat/9.0.37, java 1.8.0_292, Linux (345.8 MB / 1.93 GB)
 * **Proxy server**: k8s Nginx-ingress
 * **Client**: safari 15.1 (17612.2.9.1.20)
 * **Language**: English

## Additional notes

![iShot2021-12-14 21 07 18](https://user-images.githubusercontent.com/214470/146004554-6db4a8d7-b79c-4c51-a99a-779d0404f31f.png)

**Comment by popeen** [comment]
I don't have access to a macbook for testing so if anyone wants to help out with the project this would be a great first issue.
