### ISSUE TITLE
Cannot click setting, home links -docker

### ISSUE THREAD

**Issue by PrzemekSkw** [popeen/Booksonic-Air#68]
Hello, I install Booksonicair with Linuxserver docker-compose imagebon Debian 11 server, miniPC Intel x64.
When I login in webui I cannot click settings and home. I must put that manually in url.
Regards.

**Comment by wtanksleyjr** [comment]
I had that too, someone just recently explained a config change that worked for me too. https://github.com/popeen/Booksonic-Air/issues/33#issuecomment-1094225253

**Comment by PrzemekSkw** [comment]
Thanks for answer but I don't know how to do that. Booksonic also don't see my audiobooks so I will look for some alternative.
Regards.
